#include "Manager.h"




void Manager::addCourse(void  client, void  course)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--125b35f8:1870898b65b:-8000:00000000000008FD begin
{
}
// section -64--88-56-1--125b35f8:1870898b65b:-8000:00000000000008FD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
